import { version } from "../package.json";
import { writeFile } from "fs/promises";
import path from "path";

async function main() {
  const outPath = path.resolve(__dirname, "../src/version.ts");
  const content = `// Autogenerated by inject-version.ts\nexport const VERSION = "${version}";\n`;
  await writeFile(outPath, content);
}

main().catch(console.error);
