import { readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const pkgPath = path.resolve(__dirname, "../package.json");
  const pkg = JSON.parse(await readFile(pkgPath, "utf-8"));
  const version = pkg.version as string;
  if (typeof version !== "string") {
    throw new Error("Invalid package.json: missing string 'version' field");
  }
  const outPath = path.resolve(__dirname, "../src/version.ts");
  const content = `// Autogenerated by inject-version.ts\nexport const VERSION = "${version}";\n`;
  await writeFile(outPath, content);
}

main().catch(console.error);
