import { readFile, writeFile } from "fs/promises";
import path from "path";

async function main() {
  const pkgPath = path.resolve(__dirname, "../package.json");
  const { version } = JSON.parse(await readFile(pkgPath, "utf-8"));
  const outPath = path.resolve(__dirname, "../src/version.ts");
  const content = `// Autogenerated by inject-version.ts\nexport const VERSION = "${version}";\n`;
  await writeFile(outPath, content);
}

main().catch(console.error);
